export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const PROFILE_PICTURE_UPLOAD_REQUEST = "PROFILE_PICTURE_UPLOAD_REQUEST";
export const PROFILE_PICTURE_UPLOAD_SUCCESS = "PROFILE_PICTURE_UPLOAD_SUCCESS";
export const PROFILE_PICTURE_UPLOAD_FAIL = "PROFILE_PICTURE_UPLOAD_FAIL";

export const PROFILE_PICTURE_UPDATE_REQUEST = "PROFILE_PICTURE_UPDATE_REQUEST";
export const PROFILE_PICTURE_UPDATE_SUCCESS = "PROFILE_PICTURE_UPDATE_SUCCESS";
export const PROFILE_PICTURE_UPDATE_FAIL = "PROFILE_PICTURE_UPDATE_FAIL";

export const LOGGED_USER_INFO_REQUEST = "LOGGED_USER_INFO_REQUEST";
export const LOGGED_USER_INFO_SUCCESS = "LOGGED_USER_INFO_SUCCESS";
export const LOGGED_USER_INFO_FAIL = "LOGGED_USER_INFO_FAIL";

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAIL = "USER_LOGOUT_FAIL";

export const EXTERNAL_USER_FETCH_REQUEST = "EXTERNAL_USER_FETCH_REQUEST";
export const EXTERNAL_USER_FETCH_SUCCESS = "EXTERNAL_USER_FETCH_SUCCESS";
export const EXTERNAL_USER_FETCH_FAIL = "EXTERNAL_USER_FETCH_FAIL";

export const USER_FOLLOW_REQUEST = "USER_FOLLOW_REQUEST";
export const USER_FOLLOW_SUCCESS = "USER_FOLLOW_SUCCESS";
export const USER_FOLLOW_FAIL = "USER_FOLLOW_FAIL";

export const USER_UNFOLLOW_REQUEST = "USER_UNFOLLOW_REQUEST";
export const USER_UNFOLLOW_SUCCESS = "USER_UNFOLLOW_SUCCESS";
export const USER_UNFOLLOW_FAIL = "USER_UNFOLLOW_FAIL";
// export const CLEAR = "CLEAR";
// export const UPDATE = "UPDATE";
// export const UPDATEPIC = "UPDATEPIC";
